#!/bin/bash

baseDir=`dirname $0`
outputDir=${baseDir}/pdf

coverImage=pic/cover.png
bookName=`cat .mkbok.yml | grep name | cut -d':' -f2 | tr -d ' '`

exclude=('figures' 'figures-dia' 'figures-source' 'latex' 'makepdfs' 'pdf' 'README')
dirContent=`ls $baseDir`
argString=""

  echo $i;

argString=zh

echo "Will generate pdf for the following languages:"
echo "	"$argString

mkdir -p $outputDir

echo 
echo "The generation process will start now."
#${baseDir}/latex/makepdf $argString

#convert -resize 50% pic/cover.png pic/cover_resize.png
#mv pic/cover_resize.png pic/cover.png
convert -page A4 $coverImage -gravity center -format pdf ebooks/cover.pdf

#pdftk A=ebooks/cover.pdf B=kaiyuanbook.zh.pdf cat A1 B2-end output kaiyuanbook.zh.book.pdf 
pdftk A=ebooks/cover.pdf B=${bookName}.zh.pdf cat A B output ${bookName}.zh.book.pdf

echo
echo "${bookName}.zh.pdf --> ${bookName}.zh.book.pdf"
