#!/bin/bash

baseDir=`dirname $0`
outputDir=${baseDir}/pdf

coverImage=pic/cover.png
bookName=`cat .mkbok.yml | grep name | cut -d':' -f2 | tr -d ' '`

exclude=('figures' 'figures-dia' 'figures-source' 'latex' 'makepdfs' 'pdf' 'README')
dirContent=`ls $baseDir`
argString=""

  echo $i;

argString=zh

echo "Will generate pdf for the following languages:"
echo "	"$argString

mkdir -p $outputDir

echo 
echo "The generation process will start now."

#convert -resize 50% pic/cover.png pic/cover_resize.png
#mv pic/cover_resize.png pic/cover.png
convert -page A4 $coverImage -gravity center -format pdf pdf/cover.pdf

pdftk A=pdf/cover.pdf B=pdf/${bookName}.zh.pdf cat A B output pdf/${bookName}.zh.book.pdf

echo
echo "pdf/${bookName}.zh.pdf --> pdf/${bookName}.zh.book.pdf"
